# Generated by Django 2.0.1 on 2018-03-31 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
